from fpdf import FPDF
from datetime import datetime
import io

class ColourVisionReport(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 15)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, 'Colour Vision Test - Professional Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Colour Vision App', 0, 0, 'C')

def generate_pdf_report(results, performance_data=None):
    pdf = ColourVisionReport()
    pdf.add_page()
    
    # 1. Basic Info
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.ln(5)

    # 2. Results Summary
    pdf.set_fill_color(236, 240, 241)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, "Test Summary", 0, 1, 'L', True)
    pdf.ln(2)
    
    pdf.set_font('Arial', '', 11)
    for res in results:
        pdf.cell(0, 8, f"- {res['test_type']}: {res['result']} (Score: {res['score']})", 0, 1)
    
    pdf.ln(10)

    # 3. Recommendation Section
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(192, 57, 43) # Reddish color for emphasis
    pdf.cell(0, 10, "Clinical Recommendation", 0, 1, 'L')
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)

    # Logic-based recommendation
    worst_score = 100
    for res in results:
        score_val = float(res['score'].strip('%'))
        if score_val < worst_score: worst_score = score_val

    if worst_score >= 85:
        rec_text = "Your results indicate normal colour vision. No immediate action is required. Regular eye check-ups are recommended to maintain eye health."
    elif worst_score >= 60:
        rec_text = "Your results suggest a Mild Colour Vision Deficiency. While this may not affect daily life significantly, you may have trouble distinguishing specific shades. It is recommended to consult an optometrist for a full clinical evaluation."
    else:
        rec_text = "Your results indicate a Significant Colour Vision Deficiency. This can affect tasks like reading charts, driving, or identifying safety signals. We strongly recommend a professional consultation with an eye specialist (ophthalmologist)."

    pdf.multi_cell(0, 8, rec_text)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 6, "DISCLAIMER: This report is for screening purposes only and does not constitute a medical diagnosis. Please consult a healthcare professional for accurate assessment.")

    # Return PDF as bytes
    return bytes(pdf.output(dest='S'))
